import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar'
import { Button } from "@/components/ui/button"
import Heart from '@/components/ui/icons/heart'
import Link from "next/link"
import cloudinary from "cloudinary"
import { Folder } from './albums/page'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



async function SideMenu() {
  const {folders} = (await cloudinary.v2.api.root_folders()) as {
    folders: Folder[]
  };
  return (
    <div className="pb-12 w-1/8 ">
      <div className="space-y-4 py-4">
        <div className="px-3 py-2">
          <h2 className="mb-2 px-4 text-lg font-semibold tracking-tight">
            Manage
          </h2>
          <div className="space-y-1 flex flex-col">
          <Button asChild 
          variant="ghost" className="hover:bg-gray-600 rounded">
      <Link href="/gallery">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
        <path strokeLinecap="round" strokeLinejoin="round" d="M2.25 15.75l5.159-5.159a2.25 2.25 0 013.182 0l5.159 5.159m-1.5-1.5l1.409-1.409a2.25 2.25 0 013.182 0l2.909 2.909m-18 3.75h16.5a1.5 1.5 0 001.5-1.5V6a1.5 1.5 0 00-1.5-1.5H3.75A1.5 1.5 0 002.25 6v12a1.5 1.5 0 001.5 1.5zm10.5-11.25h.008v.008h-.008V8.25zm.375 0a.375.375 0 11-.75 0 .375.375 0 01.75 0z" />
      </svg>
      Gallery
      </Link>
    </Button>

    <Button
    asChild
    variant="secondary" className="hover:bg-gray-600 rounded">
    <Link href='/albums'>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" className="w-6 h-6">
  <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 12.75V12A2.25 2.25 0 014.5 9.75h15A2.25 2.25 0 0121.75 12v.75m-8.69-6.44l-2.12-2.12a1.5 1.5 0 00-1.061-.44H4.5A2.25 2.25 0 002.25 6v12a2.25 2.25 0 002.25 2.25h15A2.25 2.25 0 0021.75 18V9a2.25 2.25 0 00-2.25-2.25h-5.379a1.5 1.5 0 01-1.06-.44z" />
</svg>

      Albums
      </Link>
    </Button>
    {folders.map((folder) => (
      <Button
      variant='ghost'
      className='w-full justify-start flex gap-2'
      asChild key={folder.name}>
        <Link 
        className='pl-8'
        href={`/albums/${folder.path}`}>{folder.name}</Link>

      </Button>
    ))}
    <Button asChild 
    variant="secondary" className="hover:bg-gray-600 rounded">
      <Link href="/Favorites">
      <Heart/>
      Favourties
      </Link>
    </Button>
          </div>
        </div>
      </div>
    </div>
  )
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='dark'>
      <body className={inter.className}>
        <div className="border-b">
          <div className="flex h-16 items-center px-4 container mx-auto">
            <div className='flex items-center'>
            <Image src="/album.png" alt='logo'
            width="60"
            height="60"
            />
            <p className='text-5xl font-extrabold text-transparent bg-clip-text bg-gradient-to-br from-gray-400 to-orange-600'>Albumize</p>
            </div>
            <div className="ml-auto flex items-center space-x-4">
              <Avatar>
                <AvatarImage src="https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e72e6ff5-b402-4e80-9707-58633d974d36/deyo1zi-3ae4c44f-c6bd-4146-b694-10426a009f44.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcL2U3MmU2ZmY1LWI0MDItNGU4MC05NzA3LTU4NjMzZDk3NGQzNlwvZGV5bzF6aS0zYWU0YzQ0Zi1jNmJkLTQxNDYtYjY5NC0xMDQyNmEwMDlmNDQucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.R1Eh7kSCZRTmQl-_cESP1zXEW30_iWKVLFACyg4zkmQ" alt="@shadcn" />
                <AvatarFallback>CN</AvatarFallback>
              </Avatar>

            </div>
          </div>
        </div>
        <div></div>
        <div className='flex'>
          <SideMenu />
          <div className='w-full px-4 pt-12'>{children}</div>
        </div>

      </body>
    </html>
  )
}
